name: cs7643-final-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9
  - matplotlib
  - scikit-learn
  - jupyter
  - numpy
  - pip
  - mlflow
  - pip:
    - skorch
    - torch
    - torchtext
    - torchvision
    - torchaudio