' -*- coding: utf-8 -*-
' Created on 2024-12-08 13:22:10 Sunday
' @author: Nikhil Kapila

@startuml
label diagrams [

{{
title Attention Augment

skinparam backgroundColor #ffffff
skinparam rectangle {
    BackgroundColor #eeeeee
    BorderColor #000000
    FontColor #000000
}

left to right direction

rectangle "Feature\nExtractor(x)" as seqx
rectangle "Attention\nMechanism(x)" as selfatt
rectangle "(+)" as plus
rectangle "(+)" as plus1
rectangle "input" as input

input --> seqx
input --> plus : Residual\nConnection
seqx --> plus
plus --> selfatt
plus --> plus1 : Residual\nConnection
selfatt --> plus1
plus1 --> out
}}

{{
title Attention Augment (Weighted)

skinparam backgroundColor #ffffff
skinparam rectangle {
    BackgroundColor #eeeeee
    BorderColor #000000
    FontColor #000000
}

left to right direction

rectangle "Feature\nExtractor(x)" as seqx
rectangle "Attention\nMechanism(x)" as selfatt
rectangle "(+)" as plus
rectangle "(+)" as plus1
rectangle "(xW)" as weight
rectangle "input" as input

input --> seqx
input --> plus : Residual\nConnection
seqx --> plus
plus --> selfatt
selfatt --> weight
weight --> plus1 : Weighted\nAttention
plus --> plus1 : Residual\nConnection
plus1 --> out
}}
]
@enduml

